stages:
  - name: Build and Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./docker/Dockerfile
          buildContext: ./
          tag: docker.dev.folio.org/platform-complete:perf-latest
          pushRemote: true
          registry: docker.dev.folio.org
        env:
          PLUGIN_BUILD_ARGS_FROM_ENV: perf-okapi.ci.folio.org, fs09000000
        cpuRequest: 100m
        cpuLimit: 1500m
        memoryRequest: 100Mi
        memoryLimit: 8Gi
timeout: 60
notification: {}